name: develop
on:
  issues:
    types:
      - labeled

permissions:
    contents: write
    issues: write
    pull-requests: write
    id-token: write
    repository-projects: write

jobs:
  develop:
    if: github.event.label.name == 'develop'
    name: develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.17.2
      - name: Check
        run: dagger call develop-pull-request --github-token GH_TOKEN --issue-id ${{ github.event.issue.number }}
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
