name: ci
on:
  push:
    branches: ["**", "!main"]

permissions:
    contents: write
    issues: write
    pull-requests: write
    id-token: write
    repository-projects: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.17.2
      - name: Check
        run: dagger call check --github-token GH_TOKEN --commit $GITHUB_SHA
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
